# Site
name: "An Engineer's Notes and Thoughts"
title: "An Engineer's Notes and Thoughts"
description: "On Startups, Management, Product, Software, and VC Investing"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
google_analytics: 'UA-X-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  alex:
    name: Alex
    display_name: AC
    avatar: 'assets/images/avatar.jpeg'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: alkchen@gmail.com
    web: https://www.solitude.net
    twitter: https://twitter.com/wowthemesnet
    description: "Author of this website"

collections:
  authors:
    # _hide_content: true
    output: true
    # permalink: /:collection/:slug:output_ext
  videos:
    # _hide_content: true
    output: true

collections:
  - authors
  - books
  
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
