# Site
name: AC's notes and thoughts
title: AC's notes and thoughts
description: "On Startups, Management, Family, Product, Software, and VC"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-X-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]

collections_dir: models
collections:
  authors:
    output: true
    permalink: /:collection/:name
  books:
    output: true
    permalink: /:collection/:title  

# Plugins
plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-paginate  
  - jekyll-seo-tag
  - jekyll-sitemap

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags  
  permalinks:
    category: '/categories/:name/'
    tag: '/tags/:name/'
  layout: posts
    
# Pagination 
paginate: 10
paginate_path: /p/:num
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]